services:
  # Database
  mysql:
    image: mysql:8.0
    container_name: tryonx-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tryonx}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root1234}
      MYSQL_USER: ${MYSQL_USER:-tryonx_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-tryonx_pass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tryonx-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: tryonx-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tryonx-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tryonx-app
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      # Database
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-tryonx}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-tryonx_user}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-tryonx_pass}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      # JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

      # Redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      # Server
      SERVER_PORT: 8080

      # Logging
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_ORG_EXAMPLE_TRYONX: DEBUG
    volumes:
      - upload_data:/app/upload
    networks:
      - tryonx-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  tryonx-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  upload_data:
